aws-tpcc-tde-medium-amd * save benchmark results to a results directory through the playbook * save terraform infrastructure inside of results directory * upload results directory and terraform directories, excluding any needed data

diff --git a/aws-tpcc-tde-medium-amd/03_execute/playbook-tpcc-run.yml b/aws-tpcc-tde-medium-amd/03_execute/playbook-tpcc-run.yml
--- a/aws-tpcc-tde-medium-amd/03_execute/playbook-tpcc-run.yml
+++ b/aws-tpcc-tde-medium-amd/03_execute/playbook-tpcc-run.yml
@@ -1,6 +1,6 @@
 ---
 - hosts: hammerdb, primary
-  name: Run HammerDB - long run
+  name: Run HammerDB - long run - TDE enabled
   gather_facts: false
   become: true
 
@@ -15,23 +15,13 @@
       become: true
       when: "'primary' in group_names"
 
-    - name: Set variables if using TDE
+    - name: Set variables when using TDE
       ansible.builtin.set_fact:
         _pg_data: "{{ pg_data_tde }}"
         _sar_cpu_filename: "sar_cpu_tde.txt"
         _sar_mem_filename: "sar_mem_tde.txt"
         _sar_disk_filename: "sar_disk_tde.txt"
         _hdb_output_filename: "hammerdb_tde_{{ tpcc_duration }}_{{ tpcc_vusers }}.out"
-      when: "{{ use_tde | bool == true }}"
-
-    - name: Set variables if not using TDE
-      ansible.builtin.set_fact:
-        _pg_data: "{{ pg_data }}"
-        _sar_cpu_filename: "sar_cpu.txt"
-        _sar_mem_filename: "sar_mem.txt"
-        _sar_disk_filename: "sar_disk.txt"
-        _hdb_output_filename: "hammerdb_{{ tpcc_duration }}_{{ tpcc_vusers }}.out"
-      when: "{{ use_tde | bool == false }}"
 
     - name: Set tpcc_runtimer
       ansible.builtin.set_fact:
@@ -131,3 +121,157 @@
         /usr/edb/as15/bin/pg_ctl -D {{ _pg_data }} -m immediate stop
       become_user: "{{ pg_owner }}"
       when: "'primary' in group_names"
+
+- hosts: hammerdb, primary
+  name: Run HammerDB - long run - TDE disabled
+  gather_facts: false
+  become: true
+
+  collections:
+    - edb_devops.edb_postgres
+
+  tasks:
+    - name: Install sysstat
+      ansible.builtin.package:
+        name: sysstat
+        state: present
+      become: true
+      when: "'primary' in group_names"
+
+    - name: Set variables when not using TDE
+      ansible.builtin.set_fact:
+        _pg_data: "{{ pg_data }}"
+        _sar_cpu_filename: "sar_cpu.txt"
+        _sar_mem_filename: "sar_mem.txt"
+        _sar_disk_filename: "sar_disk.txt"
+        _hdb_output_filename: "hammerdb_{{ tpcc_duration }}_{{ tpcc_vusers }}.out"
+
+    - name: Set tpcc_runtimer
+      ansible.builtin.set_fact:
+        tpcc_runtimer: "{{ tpcc_rampup | int * 60 + tpcc_duration | int * 60 }}"
+
+    - name: Generate HammerDB runner script
+      ansible.builtin.template:
+        src: runner.tcl.j2
+        dest: "{{ hammerdb_data_path }}/runner.tcl"
+      when: "'hammerdb' in group_names"
+
+    - name: "Start the database with TDE={{ use_tde }}"
+      ansible.builtin.command: >
+        /usr/edb/as15/bin/pg_ctl -D {{ _pg_data }} -l {{ _pg_data }}/postgresql.log start
+      become_user: "{{ pg_owner }}"
+      when: "'primary' in group_names"
+
+    - name: Wait for Postgres to be ready
+      ansible.builtin.command:
+        cmd: >
+          /usr/edb/as15/bin/pg_isready -d postgres
+      become_user: "{{ pg_owner }}"
+      register: pg_isready
+      until: "pg_isready is not failed"
+      retries: 10
+      delay: 10
+      when: "'primary' in group_names"
+
+    - name: Drop the TPCC database if exists
+      ansible.builtin.command: >
+        /usr/edb/as15/bin/psql -d postgres -c "DROP DATABASE IF EXISTS tpcc"
+      become_user: "{{ pg_owner }}"
+      when: "'primary' in group_names"
+
+    - name: Populate the TPCC database
+      ansible.builtin.command:
+        cmd: "./hammerdbcli tcl auto {{ hammerdb_data_path }}/loader.tcl"
+        chdir: "{{ hammerdb_install_path }}"
+      changed_when: false
+      when: "'hammerdb' in group_names"
+
+    - name: CHECKPOINT
+      ansible.builtin.command: >
+        /usr/edb/as15/bin/psql -d postgres -c "CHECKPOINT"
+      become_user: "{{ pg_owner }}"
+      when: "'primary' in group_names"
+
+    - name: Start system metrics collections
+      ansible.builtin.shell: |
+        nohup sar 30 $(({{ tpcc_runtimer }} / 30)) > /tmp/{{ _sar_cpu_filename }} 2>&1&
+        nohup sar -r 30 $(({{ tpcc_runtimer }} / 30)) > /tmp/{{ _sar_mem_filename }} 2>&1&
+        nohup sar -p -d 30 $(({{ tpcc_runtimer }} / 30)) > /tmp/{{ _sar_disk_filename }} 2>&1&
+      become: true
+      when: "'primary' in group_names"
+
+    - name: Execute the long HammerDB run
+      ansible.builtin.shell: |
+        ./hammerdbcli tcl auto {{ hammerdb_data_path }}/runner.tcl > {{ hammerdb_data_path }}/{{ _hdb_output_filename }}
+      args:
+        chdir: "{{ hammerdb_install_path }}"
+      when: "'hammerdb' in group_names"
+
+    - name: Fetch data files from Postgres server
+      ansible.builtin.fetch:
+        src: "/tmp/{{ item }}"
+        dest: "./benchmark_data/{{ item }}"
+        flat: true
+      when: "'primary' in group_names"
+      register: fetch_postgres_data
+      retries: 20
+      delay: 10
+      until: fetch_postgres_data is not failed
+      become: true
+      loop:
+      - "{{ _sar_cpu_filename }}"
+      - "{{ _sar_mem_filename }}"
+      - "{{ _sar_disk_filename }}"
+
+    - name: Fetch data files from HammerDB machine
+      ansible.builtin.fetch:
+        src: "{{ hammerdb_data_path }}/{{ item }}"
+        dest: "./benchmark_data/{{ item }}"
+        flat: true
+      when: "'hammerdb' in group_names"
+      become: true
+      loop:
+      - "{{ _hdb_output_filename }}"
+
+    - name: Drop the TPCC database
+      ansible.builtin.command: >
+        /usr/edb/as15/bin/psql -d postgres -c "DROP DATABASE tpcc"
+      become_user: "{{ pg_owner }}"
+      when: "'primary' in group_names"
+
+    - name: "Stop the database with TDE={{ use_tde }}"
+      ansible.builtin.command: >
+        /usr/edb/as15/bin/pg_ctl -D {{ _pg_data }} -m immediate stop
+      become_user: "{{ pg_owner }}"
+      when: "'primary' in group_names"
+
+- hosts: localhost
+  name: post-processing on localhost
+  gather_facts: false
+  become: false
+  tasks:
+    - name: Generate final data points and chart
+      # FIXME: Dirty hack in the interest of time.  Let the post-processing.py script
+      # process what it can and fix the broken parts later.  This also let's us not
+      # worry about whether all the files exists for the push_results steps, meaning
+      # we don't have to hack that for the time being.
+      ansible.builtin.shell:
+        cmd: |
+          # Some distros use python for python3 since python2 is EOL
+          if command -v python3 > /dev/null
+          then
+            PLAYBOOK_PYTHON="python3"
+          else
+            PLAYBOOK_PYTHON="python"
+          fi
+          $PLAYBOOK_PYTHON {{ playbook_dir }}/post-processing.py || echo "ignoring errors"
+
+    - name: Copy data to results directory
+      ansible.builtin.copy:
+        src: "./benchmark_data/"
+        dest: "{{ results_directory }}/"
+
+    - name: Discard temporary data directory
+      ansible.builtin.file:
+        path: "./benchmark_data/"
+        state: absent
